### ISSUE TITLE
can you share the database webrtc-experiment

### ISSUE THREAD

**Issue by amarnath-saitech** [abdulsalam944/rummy#1]
We are getting following error

error: the firebase database 'webrtc-experiment' has reached its peak connections limit. if you are the firebase owner, consider upgrading.

how to fix it...

**Comment by abdulsalam944** [comment]
Hi, sorry I cant share you the database for some reason. I would suggest you create a firebase database, give it an authentication, and change the firebase connection with your details. As I was using a free version that why this error was coming.

**Comment by amarnath-saitech** [comment]
Thank you

**Comment by amarnath-saitech** [comment]
please share database structure for rummy game. some table is missing. like (real_wallet, bonus_details). so share missing table only.
